
package org.mesutormanli.ibbwsclient.iett.hatdurakguzergah;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebService1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService1Soap {


    /**
     * 
     * @param durakKodu
     * @return
     *     returns org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetDurakXMLResponse.GetDurakXMLResult
     */
    @WebMethod(operationName = "GetDurak_XML", action = "http://tempuri.org/GetDurak_XML")
    @WebResult(name = "GetDurak_XMLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDurak_XML", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetDurakXML")
    @ResponseWrapper(localName = "GetDurak_XMLResponse", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetDurakXMLResponse")
    public org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetDurakXMLResponse.GetDurakXMLResult getDurakXML(
        @WebParam(name = "DurakKodu", targetNamespace = "http://tempuri.org/")
        String durakKodu);

    /**
     * 
     * @param durakKodu
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDurak_json", action = "http://tempuri.org/GetDurak_json")
    @WebResult(name = "GetDurak_jsonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDurak_json", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetDurakJson")
    @ResponseWrapper(localName = "GetDurak_jsonResponse", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetDurakJsonResponse")
    public String getDurakJson(
        @WebParam(name = "DurakKodu", targetNamespace = "http://tempuri.org/")
        String durakKodu);

    /**
     * 
     * @return
     *     returns org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetGarajXMLResponse.GetGarajXMLResult
     */
    @WebMethod(operationName = "GetGaraj_XML", action = "http://tempuri.org/GetGaraj_XML")
    @WebResult(name = "GetGaraj_XMLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetGaraj_XML", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetGarajXML")
    @ResponseWrapper(localName = "GetGaraj_XMLResponse", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetGarajXMLResponse")
    public org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetGarajXMLResponse.GetGarajXMLResult getGarajXML();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGaraj_json", action = "http://tempuri.org/GetGaraj_json")
    @WebResult(name = "GetGaraj_jsonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetGaraj_json", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetGarajJson")
    @ResponseWrapper(localName = "GetGaraj_jsonResponse", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.hatdurakguzergah.GetGarajJsonResponse")
    public String getGarajJson();

}
