
package org.mesutormanli.ibbwsclient.iett.duyurular;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DuyurularSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DuyurularSoap {


    /**
     * 
     * @return
     *     returns org.mesutormanli.ibbwsclient.iett.duyurular.GetDuyurularXMLResponse.GetDuyurularXMLResult
     */
    @WebMethod(operationName = "GetDuyurular_XML", action = "http://tempuri.org/GetDuyurular_XML")
    @WebResult(name = "GetDuyurular_XMLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDuyurular_XML", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.duyurular.GetDuyurularXML")
    @ResponseWrapper(localName = "GetDuyurular_XMLResponse", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.duyurular.GetDuyurularXMLResponse")
    public org.mesutormanli.ibbwsclient.iett.duyurular.GetDuyurularXMLResponse.GetDuyurularXMLResult getDuyurularXML();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDuyurular_json", action = "http://tempuri.org/GetDuyurular_json")
    @WebResult(name = "GetDuyurular_jsonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDuyurular_json", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.duyurular.GetDuyurularJson")
    @ResponseWrapper(localName = "GetDuyurular_jsonResponse", targetNamespace = "http://tempuri.org/", className = "org.mesutormanli.ibbwsclient.iett.duyurular.GetDuyurularJsonResponse")
    public String getDuyurularJson();

}
